version: "3.9"
services:
  music_rating_server:
    container_name: music_rating_server
    build:
      context: .
      dockerfile: server.Dockerfile
    image: php:7.4-apache
    depends_on:
      - music_rating_db
    volumes:
      - ../server:/var/www/html
      - /demo.apache.conf:/etc/apache2/sites-enabled/demo.conf
      # - ./Config.php:/var/www/html/src/config/Config.php
    networks:
      - music_rating_network
    ports:
      - 8000:80
  music_rating_db:
    container_name: music_rating_db
    build:
      context: .
      dockerfile: mysql.Dockerfile
    image: mysql
    restart: always
    environment:
      MYSQL_USER: aloeffler
      MYSQL_PASSWORD: 123#@!
      MYSQL_ROOT_PASSWORD: 123#@!
    ports:
      - "3306:3306"
    volumes: 
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./backup:/backup
      - ./backup/log:/var/log
    networks:
      - music_rating_network
  music_rating_client:
    build:
      context: ..
      dockerfile: ./env/react.Dockerfile
    ports:
      - "80:3000"
    container_name: music_rating_client
    stdin_open: true
    volumes:
       - ../client:/usr/app
       - /usr/app/node_modules
networks:
    music_rating_network:
        driver: bridge